// AUTO-GENERATED by scripts/analyze-car.mjs — DO NOT HAND-EDIT.
// Re-run `npm run analyze-car` after the source GLB changes to refresh these numbers.
//
// Source: public/assets/car/volvo-s90.glb (exported Volvo S90 4-door sedan, replacing the
// Mustang-65 hero asset). Axis convention (confirmed empirically from the file, not assumed):
// Y-up, X-right (width), +Z forward (length); front-left wheel at +X/+Z. Every part is a
// top-level node with an IDENTITY transform (pose + game-frame reorient baked into vertices
// at export time, same convention as the Mustang split), so every worldQuat below is identity.
// Car root sits with wheel bottoms at world Y ~ 0.
// Generated: 2026-07-11T23:28:10.161Z

export interface Vec3Mm { readonly 0: number; readonly 1: number; readonly 2: number }
export interface Vec4 { readonly 0: number; readonly 1: number; readonly 2: number; readonly 3: number }

export interface NodeBox {
  /** World-space AABB center at load time (car root at scene origin), millimeters. */
  centerMm: Vec3Mm;
  /** World-space AABB size, millimeters. */
  sizeMm: Vec3Mm;
}

export interface WheelNode extends NodeBox {
  node: string;
  radiusMm: number;
  widthMm: number;
  /** Rim / brake pad / brake disc / tire child node names (empty for the flat Mustang parts). */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time (car root at scene origin).
   * For the Mustang split every part carries an IDENTITY transform (pose baked into vertices), so this
   * is [0,0,0,1] for all nodes — wheels.ts strips authored wheel rotation regardless (a wheel is
   * rotationally symmetric about its hub, so any authored spin is discarded).
   */
  worldQuat: Vec4;
}

export interface PanelNode extends NodeBox {
  node: string;
  /** Sub-nodes that move as one rigid group with this panel (empty for the flat Mustang parts). */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time. Identity for the Mustang
   * (baked transforms); panels.ts still composes chassisSpawnRotation * worldQuat when spawning/welding
   * each panel body, which reduces to the bare chassis rotation when worldQuat is identity.
   */
  worldQuat: Vec4;
}

export interface ChassisNode extends NodeBox {
  node: string;
  /** See WheelNode/PanelNode's worldQuat doc comment — identity for the Mustang parts. */
  worldQuat: Vec4;
}

export interface GlassMaterial {
  name: string;
  transmissionFactor: number;
}

export interface LogoSanitizeEntry {
  /** glTF/three.js material name to patch at load time. */
  name: string;
  /** Texture slot on the built THREE.MeshStandardMaterial to clear. */
  slot: 'map' | 'emissiveMap';
  reason: string;
}

export interface CarMap {
  sourceFile: string;
  generatedAt: string;
  axisConvention: string;
  overallDimsMm: { length: number; width: number; height: number };
  /** World-space center of the whole-body AABB, mm (X≈0, Y≈height/2, Z non-zero: front/rear asymmetry). */
  overallCenterMm: Vec3Mm;
  wheelbaseMm: number;
  trackFrontMm: number;
  trackRearMm: number;
  wheels: {
    frontLeft: WheelNode;
    frontRight: WheelNode;
    rearLeft: WheelNode;
    rearRight: WheelNode;
  };
  panels: Record<string, PanelNode>;
  chassis: Record<string, ChassisNode>;
  materialVariants: string[];
  /** Index into materialVariants selected at load (see render/car.ts). 0 when the asset has no variants. */
  chosenVariantIndex: number;
  glassMaterials: GlassMaterial[];
  glassMeshNodes: string[];
  /**
   * Materials carrying a trademarked logo texture to neutralize at load (scene/car.ts clears these
   * texture slots). Empty for the Mustang asset (no logo textures — all flat color factors).
   */
  logoMaterialsToSanitize: LogoSanitizeEntry[];
}

export const CAR_MAP: CarMap = {
  "sourceFile": "public/assets/car/volvo-s90.glb",
  "generatedAt": "2026-07-11T23:28:10.161Z",
  "axisConvention": "Y-up, X-right (width), Z-forward (length); left/front-left wheel at +X/+Z; wheel-bottoms ~ Y=0; identity node transforms (baked)",
  "overallDimsMm": {
    "length": 5002,
    "width": 2011,
    "height": 1434
  },
  "overallCenterMm": [
    0,
    717,
    16
  ],
  "wheelbaseMm": 2940,
  "trackFrontMm": 1629,
  "trackRearMm": 1629,
  "wheels": {
    "frontLeft": {
      "node": "WheelFL",
      "centerMm": [
        816,
        363,
        1610
      ],
      "sizeMm": [
        246,
        719,
        719
      ],
      "radiusMm": 359,
      "widthMm": 246,
      "childNodes": [
        "BrakeDiscFL",
        "CaliperFL",
        "RimBoltFL",
        "RimEmblemFL",
        "RimFL",
        "TireFL",
        "WheelhubFL"
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "frontRight": {
      "node": "WheelFR",
      "centerMm": [
        -813,
        359,
        1611
      ],
      "sizeMm": [
        246,
        719,
        719
      ],
      "radiusMm": 359,
      "widthMm": 246,
      "childNodes": [
        "BrakeDiscFR",
        "CaliperFR",
        "RimBoltFR",
        "RimEmblemFR",
        "RimFR",
        "TireFR",
        "WheelhubFR"
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "rearLeft": {
      "node": "WheelRL",
      "centerMm": [
        816,
        359,
        -1330
      ],
      "sizeMm": [
        246,
        719,
        719
      ],
      "radiusMm": 359,
      "widthMm": 246,
      "childNodes": [
        "BrakeDiscRL",
        "CaliperRL",
        "RimBoltRL",
        "RimEmblemRL",
        "RimRL",
        "TireRL",
        "WheelhubRL"
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "rearRight": {
      "node": "WheelRR",
      "centerMm": [
        -813,
        359,
        -1329
      ],
      "sizeMm": [
        246,
        719,
        719
      ],
      "radiusMm": 359,
      "widthMm": 246,
      "childNodes": [
        "BrakeDiscRR",
        "CaliperRR",
        "RimBoltRR",
        "RimEmblemRR",
        "RimRR",
        "TireRR",
        "WheelhubRR"
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "panels": {
    "Hood": {
      "node": "Hood",
      "centerMm": [
        0,
        898,
        1690
      ],
      "sizeMm": [
        1619,
        270,
        1394
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorL": {
      "node": "DoorL",
      "centerMm": [
        750,
        833,
        341
      ],
      "sizeMm": [
        350,
        1087,
        1206
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorR": {
      "node": "DoorR",
      "centerMm": [
        -750,
        833,
        341
      ],
      "sizeMm": [
        350,
        1087,
        1206
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorRL": {
      "node": "DoorRL",
      "centerMm": [
        752,
        838,
        -623
      ],
      "sizeMm": [
        357,
        1075,
        1021
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorRR": {
      "node": "DoorRR",
      "centerMm": [
        -752,
        838,
        -623
      ],
      "sizeMm": [
        357,
        1075,
        1021
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "Trunk": {
      "node": "Trunk",
      "centerMm": [
        0,
        842,
        -2131
      ],
      "sizeMm": [
        1283,
        485,
        567
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "chassis": {
    "BodyShell": {
      "node": "BodyShell",
      "centerMm": [
        0,
        802,
        16
      ],
      "sizeMm": [
        2011,
        1235,
        5002
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "EngineBlock": {
      "node": "EngineBlock",
      "centerMm": [
        13,
        569,
        1737
      ],
      "sizeMm": [
        1075,
        630,
        1110
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "materialVariants": [],
  "chosenVariantIndex": 0,
  "glassMaterials": [
    {
      "name": "Glass",
      "transmissionFactor": 0
    },
    {
      "name": "Translucent_Glass",
      "transmissionFactor": 1
    },
    {
      "name": "Translucent_Glass.001",
      "transmissionFactor": 1
    },
    {
      "name": "Glass Taillight",
      "transmissionFactor": 1
    },
    {
      "name": "Glass_wavey",
      "transmissionFactor": 1
    },
    {
      "name": "Black Glass",
      "transmissionFactor": 1
    },
    {
      "name": "GlassRunninglight",
      "transmissionFactor": 1
    },
    {
      "name": "turnsignal",
      "transmissionFactor": 1
    },
    {
      "name": "heaxagon glass",
      "transmissionFactor": 1
    }
  ],
  "glassMeshNodes": [
    "Sunroof",
    "Windshield",
    "RearWindow",
    "QuarterGlass",
    "Diffuser TrunkTaillight",
    "Diffusers Taillight",
    "Taillight glass",
    "Diffuser ReverseLight",
    "Glass Headlight",
    "Glass Runninglight",
    "Glass Turnsignal",
    "Emblem Front",
    "FrontCamera"
  ],
  "logoMaterialsToSanitize": []
};
