// AUTO-GENERATED by scripts/analyze-car.mjs — DO NOT HAND-EDIT.
// Re-run `npm run analyze-car` after the source GLB changes to refresh these numbers.
//
// Source: public/assets/car/CarConcept.glb (Khronos glTF-Sample-Assets "CarConcept", CC-BY-4.0)
// Generated: 2026-07-09T10:36:47.436Z
// Axis convention (confirmed empirically from the file, not assumed): glTF standard
// Y-up, X-right (car width), Z (car length, +Z ~ front). Car root sits with wheel
// bottoms at world Y ~ 0 (identity root transform) — safe to place at scene origin.

export interface Vec3Mm { readonly 0: number; readonly 1: number; readonly 2: number }
export interface Vec4 { readonly 0: number; readonly 1: number; readonly 2: number; readonly 3: number }

export interface NodeBox {
  /** World-space AABB center at load time (car root at scene origin), millimeters. */
  centerMm: Vec3Mm;
  /** World-space AABB size, millimeters. */
  sizeMm: Vec3Mm;
}

export interface WheelNode extends NodeBox {
  node: string;
  radiusMm: number;
  widthMm: number;
  /** Rim / brake pad / brake disc / tire child node names. */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time (car root at scene
   * origin) -- the TRS-chain transform of the NODE itself, NOT derived from mesh geometry. All 4
   * wheel nodes sit under 'BodyUnderside' (a baked -90deg-about-X ancestor) AND additionally carry
   * their own non-identity local rotation (unlike the panels below, whose own local quat is
   * identity) -- measured per-wheel: FL/FR/RL/RR each differ from identity by a different angle
   * (~30/45/160/145deg), which is why wheels.ts fully strips this (does not merely subtract a
   * shared ancestor offset) rather than deriving a "corrected" pose from it.
   */
  worldQuat: Vec4;
}

export interface PanelNode extends NodeBox {
  node: string;
  /** Sub-nodes that move as one rigid group with this panel (glass, mirrors, handles, trim). */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time (car root at scene
   * origin) -- the TRS-chain transform of the NODE itself, NOT derived from mesh geometry. All 5
   * damage panels sit under 'BodyUnderside', which carries a baked -90deg-about-X rotation (each
   * panel's OWN local quat is identity, so this equals BodyUnderside's world quat exactly);
   * panels.ts spawns each panel's PHYSICS body at chassisSpawnRotation * worldQuat (composed, not
   * replacing) and welds it there, so the body's rest orientation matches the mesh's actual
   * rendered orientation instead of the chassis's bare rotation.
   */
  worldQuat: Vec4;
}

export interface ChassisNode extends NodeBox {
  node: string;
  /** See WheelNode/PanelNode's worldQuat doc comment -- recorded here for BodyUnderside/Engine/
   * Axles/InteriorCage too, mainly as a cross-check reference (BodyUnderside's own worldQuat is
   * exactly the -90deg-about-X ancestor rotation panels/wheels inherit). */
  worldQuat: Vec4;
}

export interface GlassMaterial {
  name: string;
  transmissionFactor: number;
}

export interface LogoSanitizeEntry {
  /** glTF/three.js material name to patch at load time. */
  name: string;
  /** Texture slot on the built THREE.MeshStandardMaterial to clear. */
  slot: 'map' | 'emissiveMap';
  reason: string;
}

export interface CarMap {
  sourceFile: string;
  generatedAt: string;
  axisConvention: string;
  overallDimsMm: { length: number; width: number; height: number };
  wheelbaseMm: number;
  trackFrontMm: number;
  trackRearMm: number;
  wheels: {
    frontLeft: WheelNode;
    frontRight: WheelNode;
    rearLeft: WheelNode;
    rearRight: WheelNode;
  };
  panels: Record<string, PanelNode>;
  chassis: Record<string, ChassisNode>;
  materialVariants: string[];
  /** Index into materialVariants selected at load (see render/car.ts). */
  chosenVariantIndex: number;
  glassMaterials: GlassMaterial[];
  glassMeshNodes: string[];
  /**
   * Materials carrying a Khronos Group / 3D Commerce trademarked logo texture,
   * found in THIS file regardless of KHR_materials_variants selection (the
   * logo is NOT variant-gated — selecting a "non-logo" variant name is not
   * sufficient by itself). scene/car.ts clears these texture slots at load.
   */
  logoMaterialsToSanitize: LogoSanitizeEntry[];
}

export const CAR_MAP: CarMap = {
  "sourceFile": "public/assets/car/CarConcept.glb",
  "generatedAt": "2026-07-09T10:36:47.436Z",
  "axisConvention": "Y-up, X-right (width), Z-forward (length); root identity transform, wheel-bottom ~ Y=0",
  "overallDimsMm": {
    "length": 4357,
    "width": 2542,
    "height": 1149
  },
  "wheelbaseMm": 2800,
  "trackFrontMm": 1952,
  "trackRearMm": 1969,
  "wheels": {
    "frontLeft": {
      "node": "WheelFrontL",
      "centerMm": [
        975,
        384,
        1486
      ],
      "sizeMm": [
        591,
        768,
        781
      ],
      "radiusMm": 390,
      "widthMm": 591,
      "childNodes": [
        "WheelFrontLRim",
        "WheelFrontLBrakePad",
        "WheelFrontLBrakeDisc"
      ],
      "worldQuat": [
        0.25000003,
        -0.25,
        0.06698731,
        0.93301269
      ]
    },
    "frontRight": {
      "node": "WheelFrontR",
      "centerMm": [
        -977,
        384,
        1484
      ],
      "sizeMm": [
        589,
        765,
        778
      ],
      "radiusMm": 389,
      "widthMm": 589,
      "childNodes": [
        "WheelFrontRRim",
        "WheelFrontRBrakePad",
        "WheelFrontRBrakeDisc"
      ],
      "worldQuat": [
        -0.36964381,
        -0.23911762,
        -0.09904576,
        0.8923991
      ]
    },
    "rearLeft": {
      "node": "WheelRearL",
      "centerMm": [
        985,
        384,
        -1314
      ],
      "sizeMm": [
        284,
        768,
        768
      ],
      "radiusMm": 384,
      "widthMm": 284,
      "childNodes": [
        "WheelRearLBrakeDisc",
        "WheelRearLBrakePad",
        "WheelRearLRim"
      ],
      "worldQuat": [
        0.98480775,
        0,
        0,
        0.17364817
      ]
    },
    "rearRight": {
      "node": "WheelRearR",
      "centerMm": [
        -984,
        384,
        -1314
      ],
      "sizeMm": [
        285,
        765,
        765
      ],
      "radiusMm": 383,
      "widthMm": 285,
      "childNodes": [
        "WheelRearRBrakeDisc",
        "WheelRearRBrakePad",
        "WheelRearRRim"
      ],
      "worldQuat": [
        0.95371695,
        0,
        0,
        -0.3007058
      ]
    }
  },
  "panels": {
    "BodyHood": {
      "node": "BodyHood",
      "centerMm": [
        0,
        503,
        1793
      ],
      "sizeMm": [
        2212,
        749,
        1249
      ],
      "childNodes": [
        "BodyHoodInterior01",
        "BodyHoodInterior02",
        "BodyHoodTopgrill",
        "BodyHoodUnder",
        "BodyHeadlights"
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "BodyDoorLColor1": {
      "node": "BodyDoorLColor1",
      "centerMm": [
        952,
        635,
        159
      ],
      "sizeMm": [
        434,
        959,
        1669
      ],
      "childNodes": [
        "InteriorDoorL04",
        "InteriorDoorL01",
        "InteriorDoorL02",
        "InteriorDoorL03",
        "InteriorDoorL05",
        "InteriorDoorL06",
        "BodyDoorLColor2",
        "BodyDoorLHandle01",
        "BodyDoorLHandle02",
        "BodyDoorLMirror",
        "BodyDoorLMirrorColor1",
        "BodyDoorLWindowGasket",
        "BodyDoorLWindow",
        "BodyDoorLMirrorColor2"
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "BodyDoorRColor1": {
      "node": "BodyDoorRColor1",
      "centerMm": [
        -952,
        635,
        159
      ],
      "sizeMm": [
        434,
        959,
        1669
      ],
      "childNodes": [
        "BodyDoorRColor2",
        "BodyDoorRHandle01",
        "BodyDoorRHandle02",
        "BodyDoorRMirror",
        "BodyDoorRMirrorColor1",
        "BodyDoorRMirrorColor2",
        "BodyDoorRWindow",
        "BodyDoorRWindowGasket",
        "InteriorDoorR01",
        "InteriorDoorR02",
        "InteriorDoorR03",
        "InteriorDoorR04",
        "InteriorDoorR05",
        "InteriorDoorR06"
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "InteriorRearHatch": {
      "node": "InteriorRearHatch",
      "centerMm": [
        0,
        1031,
        -1027
      ],
      "sizeMm": [
        1798,
        213,
        1195
      ],
      "childNodes": [],
      "worldQuat": [
        -0.70710695,
        0,
        0,
        0.70710661
      ]
    },
    "BodyRoofPanel": {
      "node": "BodyRoofPanel",
      "centerMm": [
        0,
        1132,
        -82
      ],
      "sizeMm": [
        1334,
        32,
        744
      ],
      "childNodes": [],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "BodyRearPanelsColor1": {
      "node": "BodyRearPanelsColor1",
      "centerMm": [
        0,
        668,
        -1185
      ],
      "sizeMm": [
        2236,
        951,
        1511
      ],
      "childNodes": [
        "InteriorRearHatch",
        "InteriorRearPanels",
        "BodyWindowsRearSides",
        "BodyTurnsignalsRear",
        "BodyTaillightsPanels",
        "BodyTaillights",
        "BodyRearwindow"
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "BodyPanelsColor2": {
      "node": "BodyPanelsColor2",
      "centerMm": [
        0,
        315,
        230
      ],
      "sizeMm": [
        2222,
        414,
        4337
      ],
      "childNodes": [],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "BodyPillars": {
      "node": "BodyPillars",
      "centerMm": [
        0,
        626,
        465
      ],
      "sizeMm": [
        2215,
        1034,
        1872
      ],
      "childNodes": [],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    }
  },
  "chassis": {
    "BodyUnderside": {
      "node": "BodyUnderside",
      "centerMm": [
        0,
        574,
        238
      ],
      "sizeMm": [
        2542,
        1149,
        4357
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "Engine": {
      "node": "Engine",
      "centerMm": [
        0,
        444,
        1964
      ],
      "sizeMm": [
        1205,
        608,
        722
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "Axles": {
      "node": "Axles",
      "centerMm": [
        0,
        384,
        91
      ],
      "sizeMm": [
        2106,
        190,
        3001
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    },
    "InteriorCage": {
      "node": "InteriorCage",
      "centerMm": [
        0,
        961,
        96
      ],
      "sizeMm": [
        1904,
        306,
        1950
      ],
      "worldQuat": [
        -0.70710678,
        0,
        0,
        0.70710678
      ]
    }
  },
  "materialVariants": [
    "Carmine Candy",
    "Pearly Swirly",
    "Torched Graphite"
  ],
  "chosenVariantIndex": 2,
  "glassMaterials": [
    {
      "name": "Glass",
      "transmissionFactor": 1
    }
  ],
  "glassMeshNodes": [
    "BodyWindshield",
    "BodyWindowsRearSides",
    "BodyRearwindow",
    "BodyDoorRWindow",
    "BodyDoorLWindow"
  ],
  "logoMaterialsToSanitize": [
    {
      "name": "License",
      "slot": "map",
      "reason": "baseColorTexture is the Khronos Group wordmark PNG (license-plate decal)"
    },
    {
      "name": "Tireside",
      "slot": "map",
      "reason": "baseColorTexture is Khronos + 3D Commerce logos (tire sidewall decal)"
    },
    {
      "name": "Hardware",
      "slot": "emissiveMap",
      "reason": "reuses the Khronos wordmark image as emissiveTexture"
    },
    {
      "name": "Mirror",
      "slot": "emissiveMap",
      "reason": "reuses the Khronos wordmark image as emissiveTexture"
    },
    {
      "name": "Brake",
      "slot": "emissiveMap",
      "reason": "reuses the Khronos wordmark image as emissiveTexture"
    },
    {
      "name": "Rim1",
      "slot": "emissiveMap",
      "reason": "reuses the Khronos wordmark image as emissiveTexture"
    },
    {
      "name": "Rim2",
      "slot": "emissiveMap",
      "reason": "reuses the Khronos wordmark image as emissiveTexture"
    }
  ]
};
