// AUTO-GENERATED by scripts/analyze-car.mjs — DO NOT HAND-EDIT.
// Re-run `npm run analyze-car` after the source GLB changes to refresh these numbers.
//
// Source: public/assets/car/mustang65.glb (Sketchfab "Rigged Car Mustang 1965 with Engine", CC-BY-4.0,
// split into named rigid parts by scripts/split-mustang.py). Axis convention (confirmed empirically
// from the file, not assumed): Y-up, X-right (width), +Z forward (length); front-left wheel at +X/+Z.
// Every part is a top-level node with an IDENTITY transform (the split baked pose + game-frame reorient
// straight into vertices), so every worldQuat below is identity — unlike the legacy CarConcept rig,
// there is no shared -90deg BodyUnderside ancestor. Car root sits with wheel bottoms at world Y ~ 0.
// Generated: 2026-07-10T00:45:07.566Z

export interface Vec3Mm { readonly 0: number; readonly 1: number; readonly 2: number }
export interface Vec4 { readonly 0: number; readonly 1: number; readonly 2: number; readonly 3: number }

export interface NodeBox {
  /** World-space AABB center at load time (car root at scene origin), millimeters. */
  centerMm: Vec3Mm;
  /** World-space AABB size, millimeters. */
  sizeMm: Vec3Mm;
}

export interface WheelNode extends NodeBox {
  node: string;
  radiusMm: number;
  widthMm: number;
  /** Rim / brake pad / brake disc / tire child node names (empty for the flat Mustang parts). */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time (car root at scene origin).
   * For the Mustang split every part carries an IDENTITY transform (pose baked into vertices), so this
   * is [0,0,0,1] for all nodes — wheels.ts strips authored wheel rotation regardless (a wheel is
   * rotationally symmetric about its hub, so any authored spin is discarded).
   */
  worldQuat: Vec4;
}

export interface PanelNode extends NodeBox {
  node: string;
  /** Sub-nodes that move as one rigid group with this panel (empty for the flat Mustang parts). */
  childNodes: string[];
  /**
   * This node's own world-space rotation quaternion [x,y,z,w] at load time. Identity for the Mustang
   * (baked transforms); panels.ts still composes chassisSpawnRotation * worldQuat when spawning/welding
   * each panel body, which reduces to the bare chassis rotation when worldQuat is identity.
   */
  worldQuat: Vec4;
}

export interface ChassisNode extends NodeBox {
  node: string;
  /** See WheelNode/PanelNode's worldQuat doc comment — identity for the Mustang parts. */
  worldQuat: Vec4;
}

export interface GlassMaterial {
  name: string;
  transmissionFactor: number;
}

export interface LogoSanitizeEntry {
  /** glTF/three.js material name to patch at load time. */
  name: string;
  /** Texture slot on the built THREE.MeshStandardMaterial to clear. */
  slot: 'map' | 'emissiveMap';
  reason: string;
}

export interface CarMap {
  sourceFile: string;
  generatedAt: string;
  axisConvention: string;
  overallDimsMm: { length: number; width: number; height: number };
  /** World-space center of the whole-body AABB, mm (X≈0, Y≈height/2, Z non-zero: front/rear asymmetry). */
  overallCenterMm: Vec3Mm;
  wheelbaseMm: number;
  trackFrontMm: number;
  trackRearMm: number;
  wheels: {
    frontLeft: WheelNode;
    frontRight: WheelNode;
    rearLeft: WheelNode;
    rearRight: WheelNode;
  };
  panels: Record<string, PanelNode>;
  chassis: Record<string, ChassisNode>;
  materialVariants: string[];
  /** Index into materialVariants selected at load (see render/car.ts). 0 when the asset has no variants. */
  chosenVariantIndex: number;
  glassMaterials: GlassMaterial[];
  glassMeshNodes: string[];
  /**
   * Materials carrying a trademarked logo texture to neutralize at load (scene/car.ts clears these
   * texture slots). Empty for the Mustang asset (no logo textures — all flat color factors).
   */
  logoMaterialsToSanitize: LogoSanitizeEntry[];
}

export const CAR_MAP: CarMap = {
  "sourceFile": "public/assets/car/mustang65.glb",
  "generatedAt": "2026-07-10T00:45:07.566Z",
  "axisConvention": "Y-up, X-right (width), Z-forward (length); left/front-left wheel at +X/+Z; wheel-bottoms ~ Y=0; identity node transforms (baked)",
  "overallDimsMm": {
    "length": 4591,
    "width": 1936,
    "height": 1309
  },
  "overallCenterMm": [
    0,
    654,
    60
  ],
  "wheelbaseMm": 2743,
  "trackFrontMm": 1619,
  "trackRearMm": 1620,
  "wheels": {
    "frontLeft": {
      "node": "WheelFL",
      "centerMm": [
        810,
        308,
        1371
      ],
      "sizeMm": [
        223,
        617,
        619
      ],
      "radiusMm": 310,
      "widthMm": 223,
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "frontRight": {
      "node": "WheelFR",
      "centerMm": [
        -809,
        308,
        1371
      ],
      "sizeMm": [
        223,
        617,
        619
      ],
      "radiusMm": 310,
      "widthMm": 223,
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "rearLeft": {
      "node": "WheelRL",
      "centerMm": [
        810,
        308,
        -1371
      ],
      "sizeMm": [
        222,
        617,
        619
      ],
      "radiusMm": 310,
      "widthMm": 222,
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "rearRight": {
      "node": "WheelRR",
      "centerMm": [
        -810,
        308,
        -1371
      ],
      "sizeMm": [
        225,
        617,
        619
      ],
      "radiusMm": 310,
      "widthMm": 225,
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "panels": {
    "Hood": {
      "node": "Hood",
      "centerMm": [
        0,
        809,
        1520
      ],
      "sizeMm": [
        1216,
        174,
        1644
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorL": {
      "node": "DoorL",
      "centerMm": [
        748,
        733,
        31
      ],
      "sizeMm": [
        313,
        839,
        1336
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "DoorR": {
      "node": "DoorR",
      "centerMm": [
        -747,
        733,
        31
      ],
      "sizeMm": [
        313,
        839,
        1336
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "Trunk": {
      "node": "Trunk",
      "centerMm": [
        0,
        811,
        -1877
      ],
      "sizeMm": [
        1404,
        139,
        591
      ],
      "childNodes": [],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "chassis": {
    "BodyShell": {
      "node": "BodyShell",
      "centerMm": [
        0,
        761,
        60
      ],
      "sizeMm": [
        1936,
        1096,
        4591
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "EngineBlock": {
      "node": "EngineBlock",
      "centerMm": [
        -17,
        501,
        1419
      ],
      "sizeMm": [
        1507,
        579,
        1036
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    },
    "Drivetrain": {
      "node": "Drivetrain",
      "centerMm": [
        0,
        450,
        -568
      ],
      "sizeMm": [
        1568,
        518,
        3049
      ],
      "worldQuat": [
        0,
        0,
        0,
        1
      ]
    }
  },
  "materialVariants": [],
  "chosenVariantIndex": 0,
  "glassMaterials": [
    {
      "name": "TransparentGlass",
      "transmissionFactor": 0
    },
    {
      "name": "refract glass",
      "transmissionFactor": 0
    }
  ],
  "glassMeshNodes": [
    "Windshield",
    "RearWindow"
  ],
  "logoMaterialsToSanitize": []
};
