import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/addons/loaders/GLTFLoader.js';
import { CAR_MAP } from '../assets/car-map';
import { polishCarMaterials } from './carMaterials';
import { splitBumpers, type BumperSplit } from './bumperSplit';

export interface CarBundle {
  root: THREE.Object3D;
  gltf: GLTF;
  glassMeshes: THREE.Mesh[];
  /** BUG R004 deliverable 2: front/rear bumper regions carved out of BodyShell at load time into their
   * own hinged, swingable meshes -- driven by main.ts/lab/main.ts each fixed step (see bumperSplit.ts).
   * Created here (BEFORE registerCarDeformables()) so the resulting shell/bumper meshes register as
   * separate deformables and the crumple/structural-sync pipeline stays consistent. */
  bumpers: BumperSplit;
}

/**
 * KHR_materials_variants isn't handled by three's GLTFLoader itself (it's an
 * "unknown extension" that the loader passes through verbatim into
 * `object.userData.gltfExtensions`) — this mirrors the official three.js
 * webgl_loader_gltf_variants example pattern: read the variant list off
 * `gltf.userData.gltfExtensions.KHR_materials_variants.variants`, then for
 * every mesh with a per-primitive mapping, swap in the material for the
 * requested variant index via `parser.getDependency('material', ...)`.
 */
async function selectVariant(gltf: GLTF, variantIndex: number): Promise<void> {
  const parser = gltf.parser;
  const tasks: Promise<void>[] = [];

  gltf.scene.traverse((object) => {
    const mesh = object as THREE.Mesh;
    if (!mesh.isMesh) return;
    const variantDef = mesh.userData?.gltfExtensions?.KHR_materials_variants;
    if (!variantDef) return;

    if (!mesh.userData.originalMaterial) {
      mesh.userData.originalMaterial = mesh.material;
    }

    const mapping = variantDef.mappings.find((m: { variants: number[] }) => m.variants.includes(variantIndex));
    tasks.push(
      (async () => {
        if (mapping) {
          mesh.material = await parser.getDependency('material', mapping.material);
          parser.assignFinalMaterial(mesh);
        } else {
          mesh.material = mesh.userData.originalMaterial;
        }
      })(),
    );
  });

  await Promise.all(tasks);
}

/**
 * Neutralizes the Khronos Group / 3D Commerce trademarked logo textures found
 * in this GLB (car-map.ts `logoMaterialsToSanitize`, generated by
 * scripts/analyze-car.mjs — see that file for exactly which images/materials
 * these are and why picking a non-branded *variant* alone does not remove
 * them: the license-plate and tire-sidewall logos are NOT gated by
 * KHR_materials_variants). Clearing the texture slot and leaving a flat
 * factor color is a material-configuration change, not asset re-authoring.
 */
function sanitizeLogoMaterials(root: THREE.Object3D): void {
  const patchedByName = new Set<string>();
  root.traverse((object) => {
    const mesh = object as THREE.Mesh;
    if (!mesh.isMesh) return;
    const materials = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    for (const mat of materials) {
      const std = mat as THREE.MeshStandardMaterial;
      if (!std || !std.name) continue;
      const entry = CAR_MAP.logoMaterialsToSanitize.find((e) => e.name === std.name);
      if (!entry) continue;
      if (entry.slot === 'map' && std.map) {
        std.map.dispose();
        std.map = null;
        // Plausible flat fallback: dark rubber for tires, neutral plate gray otherwise.
        std.color = entry.name === 'Tireside' ? new THREE.Color(0x161616) : new THREE.Color(0x9a9a9a);
        std.roughness = entry.name === 'Tireside' ? 0.92 : 0.7;
        std.needsUpdate = true;
      } else if (entry.slot === 'emissiveMap' && std.emissiveMap) {
        std.emissiveMap.dispose();
        std.emissiveMap = null;
        std.emissive = new THREE.Color(0x000000);
        std.needsUpdate = true;
      }
      patchedByName.add(std.name);
    }
  });
  const missed = CAR_MAP.logoMaterialsToSanitize.filter((e) => !patchedByName.has(e.name));
  if (missed.length > 0) {
    // Not fatal (material names are stable across variants in this file), but
    // surface it loudly rather than silently ship a trademark logo.
    console.warn('[car] expected logo materials not found in loaded scene:', missed.map((m) => m.name));
  }
}

export async function loadCar(url: string): Promise<CarBundle> {
  const loader = new GLTFLoader();
  const gltf = await loader.loadAsync(url);

  await selectVariant(gltf, CAR_MAP.chosenVariantIndex);
  sanitizeLogoMaterials(gltf.scene);
  // Paint/glass tuning for the outdoor je_gray_02 HDRI (see carMaterials.ts's module doc comment) --
  // MUST run before the glassMeshes traversal below and before returning, so every downstream
  // consumer (carDeformables registration, glass-shatter clone in main.ts) captures these materials.
  polishCarMaterials(gltf.scene);

  const glassMeshes: THREE.Mesh[] = [];
  gltf.scene.traverse((object) => {
    const mesh = object as THREE.Mesh;
    if (!mesh.isMesh) return;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    const mat = mesh.material as THREE.MeshPhysicalMaterial;
    if (mat && CAR_MAP.glassMeshNodes.includes(mesh.name || mesh.parent?.name || '')) {
      glassMeshes.push(mesh);
      mesh.castShadow = false; // avoid transparent glass casting a solid shadow blob
    }
  });

  // BUG R004 (deliverable 2): carve the front/rear bumper regions out of the BodyShell primitives into
  // their own hinged meshes -- MUST run here (after material polish/shadow flags, before the caller's
  // registerCarDeformables()) so the split shell + bumper meshes are what gets registered. Runs before
  // detachWheelVisuals() too, but only touches the BodyShell subtree, so wheels are unaffected.
  const bumpers = splitBumpers(gltf.scene);

  return { root: gltf.scene, gltf, glassMeshes, bumpers };
}
