// SPDX-License-Identifier: MIT
//
// Detaches the 4 wheel node groups (WheelFrontL/R, WheelRearL/R -- each already carries its rim/
// brake-pad/brake-disc children per car-map.ts) from the loaded car hierarchy and re-parents them
// directly under the scene, so each can be driven independently from its own physics wheel body's
// transform every frame instead of riding the chassis's single transform.

import * as THREE from 'three';
import { CAR_MAP } from '../assets/car-map';
import type { WheelKey } from '../vehicle/vehicle';
import { InterpolatedTransform } from '../core/loop';

const WHEEL_NODE_NAMES: Record<WheelKey, string> = {
	fl: CAR_MAP.wheels.frontLeft.node,
	fr: CAR_MAP.wheels.frontRight.node,
	rl: CAR_MAP.wheels.rearLeft.node,
	rr: CAR_MAP.wheels.rearRight.node,
};

/**
 * FIX (was: neutralizeSteerYaw() below, applied to front wheels only, removing just the yaw-about-
 * world-up component). Measured directly (car-map.ts's WheelNode.worldQuat, generated by
 * scripts/analyze-car.mjs): each of the 4 wheel nodes carries its OWN non-identity local rotation on
 * top of the shared 'BodyUnderside' ancestor tilt (unlike the 5 damage panels, whose own local quat is
 * identity) -- a static authoring defect with NO consistent relationship between wheels: measured
 * angle from identity is ~42deg (FL), ~54deg (FR), ~160deg (RL), ~145deg (RR) (see
 * game/verify/diag/wheel-quat-check.mjs), so a partial fix (stripping only steering yaw) left a
 * residual per-wheel tilt that differed wheel-to-wheel (FL 30deg vs FR 45deg after the old partial
 * strip, rears untouched at 160/145deg). Since a wheel is rotationally symmetric about its own hub
 * axis, none of this authored rotation is visually meaningful -- discard it ENTIRELY for all 4 wheels
 * (fronts AND rears) rather than attempting to salvage a "camber" component from admittedly-buggy
 * authoring data. The wheel body's own rotation (near-identity at spawn, then steering/spin driven by
 * physics) is applied as the sole visual orientation from here on -- see applyWheelVisual().
 */
const NEUTRAL_QUAT = new THREE.Quaternion();

export interface WheelVisual {
	object: THREE.Object3D;
	transform: InterpolatedTransform;
	/**
	 * The wheel visual's "neutral" base orientation, applied as the frame the physics body's rotation
	 * delta is layered onto (see applyWheelVisual()). Always NEUTRAL_QUAT (identity) now -- kept as a
	 * per-instance field (rather than inlining NEUTRAL_QUAT directly in applyWheelVisual()) so this
	 * type/call shape stays stable if a future asset ever needs a real per-wheel baseline again.
	 */
	initialWorldQuat: THREE.Quaternion;
}

/** Finds each wheel group node by name (car-map.ts), detaches it from the car hierarchy, and
 * re-parents it under `scene` directly, preserving its current world transform at detach time. */
export function detachWheelVisuals(carRoot: THREE.Object3D, scene: THREE.Scene): Record<WheelKey, WheelVisual> {
	const result = {} as Record<WheelKey, WheelVisual>;
	for (const key of Object.keys(WHEEL_NODE_NAMES) as WheelKey[]) {
		const nodeName = WHEEL_NODE_NAMES[key];
		const object = carRoot.getObjectByName(nodeName);
		if (!object) {
			console.warn(`[wheels] expected wheel node "${nodeName}" not found in loaded car scene`);
			continue;
		}
		const worldPos = new THREE.Vector3();
		const worldQuat = new THREE.Quaternion();
		const worldScale = new THREE.Vector3();
		object.updateWorldMatrix(true, false);
		object.matrixWorld.decompose(worldPos, worldQuat, worldScale); // worldQuat unused for rotation
		// (see NEUTRAL_QUAT's doc comment) -- only worldPos/worldScale are kept from this decompose.

		scene.attach(object); // re-parents while preserving world transform (position/scale only --
		// rotation is overridden below)
		object.position.copy(worldPos);
		object.quaternion.copy(NEUTRAL_QUAT); // strip ALL authored rotation, fronts AND rears
		object.scale.copy(worldScale);

		result[key] = { object, transform: new InterpolatedTransform(), initialWorldQuat: NEUTRAL_QUAT.clone() };
	}
	return result;
}

const scratchDelta = new THREE.Quaternion();
const scratchPos = new THREE.Vector3();
const scratchQuat = new THREE.Quaternion();

/** Applies one wheel visual's interpolated physics transform (position direct, rotation as a delta
 * on top of its preserved authored orientation) for the current render frame. */
export function applyWheelVisual(visual: WheelVisual, spawnBodyQuat: THREE.Quaternion, alpha: number): void {
	visual.transform.lerpPosition(scratchPos, alpha);
	visual.transform.lerpQuaternion(scratchQuat, alpha);
	// delta = currentBodyQuat * inverse(spawnBodyQuat) -- the rotation the physics body has
	// undergone since spawn, expressed in world space, then applied on top of the mesh's original
	// (authored) world orientation.
	scratchDelta.copy(spawnBodyQuat).invert();
	scratchDelta.premultiply(scratchQuat);
	visual.object.position.copy(scratchPos);
	visual.object.quaternion.copy(scratchDelta).multiply(visual.initialWorldQuat);
}
